version: 0.1

name: Deploy Angular App
container_tags:
  - my-angular-app:latest
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Angular App
    runs-on: linux
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install Dependencies
        run: npm install --force
      - name: Build Angular App
        run: npm run build --if-present
      - name: systemctl restart nginx.service
        run: systemctl restart nginx.service
      - artifacts:
          files:
          - '**/*'
